### ISSUE TITLE
attachx

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/dwm-vanitygaps#3]
the attachx patch isn't behaving properly... how do I explain it ... em
for example ...

I have a few windows on my 2nd tag, and I have discord on my 9th tag, when I right click the 9th tag to display it at the 2nd tag as well, it uses the default behavior instead of respecting the attachx settings ... I have tested this on separate attach patches and they work properly

**Comment by kronikpillow** [comment]
funny, building your full build, the attachx works perfectly on any settings, while applying it to a clean dwm build it uses default behavior when I right click for example the app on 9th tag to show on the first tag

**Comment by bakkeby** [comment]
Hi @kronikpillow,

I tested this and I think I see the behaviour that you are referring to. I don't think this has anything to do with the attachx patch or the individual attach above/aside/below/bottom patches.

In dwm all clients live in a single linked list. If you open a new client, e.g. a terminal, then that client by default will be added to the start of the list.

The attach bottom patch is the opposite, new clients are always added at the end of the list.

The attach above / aside / below patches all try to add new clients within the list relative to other displayed clients. If there are no clients on the current tag then the new client will be added to the start of the list as normal.

When you right click on the 9th tag to also show the discord application all that is happening is that dwm knows that clients on both tag 2 and tag 9 are to be displayed. It will go through the list sequentially, checking if the client is to be displayed or not.

Because you opened discord _after_ the clients on the 2nd tag it will appear in the master area, because it is the first displayable client in the list.

You can test this by opening your discord application on the 9th tag first, then start your other applications on tag 2. When you right click on the 9th tag you'll see that the discord shows up in the slave area.

If you open a new client when both tag 2 and tag 9 are displayed, then that client will be shown on both tag 2 and tag 9 individually as well. Given the way clients are ordered in a single linked list the ordering on both tags would only be consistent with the attach bottom and the default (attach master / top) methods.

Hope this makes sense.


Thanks,

-Stein

**Comment by kronikpillow** [comment]
yes, I found out that TAGINTOSTACK_ALLMASTER_PATCH gives me the functionality I want :) Thanks for your time.
