### ISSUE TITLE
Error during the compiling process

### ISSUE THREAD

**Issue by igorlakic** [bakkeby/dwm-vanitygaps#6]
When I try to compile dwm from your configuration I get this:
```
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\"6.2\" -DXINERAMA dwm.c
In file included from dwm.c:346:0:
config.h:44:27: error: initializer element is not constant
  [SchemeNorm] = { OPAQUE, baralpha, borderalpha },
                           ^~~~~~~~
config.h:44:27: note: (near initialization for ‘alphas[0][1]’)
config.h:44:37: error: initializer element is not constant
  [SchemeNorm] = { OPAQUE, baralpha, borderalpha },
                                     ^~~~~~~~~~~
config.h:44:37: note: (near initialization for ‘alphas[0][2]’)
config.h:45:27: error: initializer element is not constant
  [SchemeSel]  = { OPAQUE, baralpha, borderalpha },
                           ^~~~~~~~
config.h:45:27: note: (near initialization for ‘alphas[1][1]’)
config.h:45:37: error: initializer element is not constant
  [SchemeSel]  = { OPAQUE, baralpha, borderalpha },
                                     ^~~~~~~~~~~
config.h:45:37: note: (near initialization for ‘alphas[1][2]’)
Makefile:18: recipe for target 'dwm.o' failed
make: *** [dwm.o] Error 1
```

I'm newbie in the DWM world (and in Suckless generally) so I would like to know if I need to configure something? I'm on Ubuntu 18.04.

Thanks in advance!

**Comment by bakkeby** [comment]
Hi Igor,

yes I have had this myself and I believe it's because of the version of gcc that is used by default in Ubuntu.

I suspect that if you check what the symlink /usr/bin/gcc refers to gcc-7.
```bash
$ ls -l /usr/bin/gcc
lrwxrwxrwx  root  root   -  Mon May 20 18:07:51 2019  gcc ⇒ gcc-7
```

You might have gcc-8 installed already, but if not then you might want to install that.
```bash
sudo apt install -y gcc-8
```

Then change the symlink to point to gcc-8 instead.
```bash
sudo ln -fs /usr/bin/gcc-8 /usr/bin/gcc
```

That should allow you to compile as intended.

Hope that helps.


-Stein

**Comment by igorlakic** [comment]
Hi Stein,

Thanks for a fast reply.
Yes, you're right, gcc was the cause of this issue. I did everything like you described above and now it compiles perfectly.👍

One small question unrelated to this issue, I would like to get your advice: would you recommend that I start using "dwm-vanitygaps" or maybe "dwm-flexipatch"? If I understand correctly, I have to patch dwm manually in this "dwm-vanitygaps" while that process more or less automatized in "dwm-flexipatch", am I right?

Thanks once again for help, keep up the good work.

-Igor

**Comment by bakkeby** [comment]
dwm-vanitygaps is in a way "my" build of dwm with the patches I have chosen (and made), with the twist that I made most of them toggleable using variables in config.h.

You can use dwm-vanitygaps as-is, but if you want any new patches then you'd have to add them yourself. The individual patches provided here are just in case you are patching from scratch with a clean 6.2 dwm.

I more or less abandoned this project when I got the idea to use preprocessor directives to decide whether or not a patch is included, and started dwm-flexipatch. That project has more than 100 patches integrated now, so the code (and configuration) will be overwhelming. My recommendation would be to not look too much at the configuration file unless it is just to see what some of the keyboard shortcuts are. The focus there is to be able to try out different combination of patches to see what works for you and what doesn't.

The "proper" way would be to start patching from scratch, to get to know the code and to make it your own (everyone rolls their own). Both of these projects just aim to save you some time selecting patches, that's all :)

**Comment by igorlakic** [comment]
Nice explanation, thanks Stein!

I'll examine your code from dwm-vanitygaps to see which patches you applied into it. I still have to make myself more familiar with all those dwm patches... From what I heard and read about dwm, it seems like the best tiling window manager so would like to give it a shoot and try use it for some time. I was thinking about switching to bspwm but I like the logic behind dwm and, for example, "tags" instead of workspaces and ability to show all open windows from various tags into one tag, which seems really handy.

My goal is to have simple panel/bar with tags on the left and system tray on the right side with some additional information aside it. Do you maybe have your bar configuration somewhere on the GitHub (so I can use it as an example)? And related to dwm layouts and other cool patches, I will have to see and decide what to use.

Do you have any recommendation for patches (some patches you simply cannot live without)?

**Comment by bakkeby** [comment]
> _From what I heard and read about dwm, it seems like the best tiling window manager_

Ha, you may want to take that with a pinch of salt :) It's a tinkerer's dream. If anyone ever says that dwm is good then that would be because they have spent those 40+ hours trying out patches, maybe even implemented some, and have fully tailored it to work exactly like they want it to work - it's good because it's good for them.

Although I use it and being very very happy with it, I can't say that I could ever _recommend_ someone to spend that amount of time fiddling with patches. To be honest it didn't take long before I started hating the patching aspects of dwm. It was time consuming and there was a lot of trial and error. Eventually I got more proficient at it and got to know the code better, even created some patches of my own. I had never done C before.

I still think dwm is worth checking out, so I started this, and eventually dwm-flexipatch, with the aim of saving newcomers some time trying out a "fully-fledged", if not to say bloated, version of dwm.

> _My goal is to have simple panel/bar with tags on the left and system tray on the right side with some additional information aside it._

I don't have much in my bar. I also don't have the configuration on github.
![image](https://user-images.githubusercontent.com/1438008/72439954-3ca98f00-37a8-11ea-8dec-e1412844d596.png)

I used a bash script in the past, but I'd recommend having a look at [slstatus](https://tools.suckless.org/slstatus/) instead.

> _Do you have any recommendation for patches (some patches you simply cannot live without)?_

Eh, yes sure. I have about 60 patches enabled on my flexipatch build, most of them are merely for convenience or just in case I were to break anything. In terms of those that I use most frequently I guess these would be some of my favourites.

In terms of layout I use the flextile deluxe layout, it's over the top, but it can do pretty much everything.

Pertag is an obvious one, being able to have different layouts and settings per tag.

Resizecorners, it's just so more intuitive to be able to resize from any corner, not just the bottom right.

Vanitygaps, because I like my gaps.

Zoomswap, because I like unrelated windows to stay in place when swapping out master. 

The attach patches are mere for behavioural preference, I use the attach aside one.

Awesomebar, I like the possibility of hiding windows.

The toggle fullscreen patch + losefullscreen patch, it's just convenient to be able to fullscreen any window using, e.g. `Mod+f`.

cfacts is also convenient when you just need a bit more space for that one window in the stack.

savefloats can also be convenient.

**Comment by kronikpillow** [comment]
@bakkeby you didn't know C before? and you did all this work alone? WOW... I want to learn C, but im broke and dunno where to start :D got any good books? :)

I also have questions about some patches in the flexipatch as it is not clear to me what their real purpose is, but I'll post them on that repo

**Comment by kronikpillow** [comment]
@igorlakic brate moj :) I was doubtfull about the flexipatch build at the beginning, and wanted to go manual patching, but then I realized, that the patches on suckless.org are pretty outdated, that some of them are missing some basic features, and that until I / you actually learn C, and how to properly patch everything, that dwm-flexipatch is the best way to go, as @bakkeby custom tweaked / updated all the patches, and they all shoul work with each other without major conflicts, the ones which conflict between each other are noted in patches.h, so for starters, if you want a functional dwm, and you actually want to test out patches, flexipatch is the best way to go in my opinion, then when and if you learn, and are eager to do the work your self about customizing the patches to your liking, manual patching is the way to go :)

**Comment by igorlakic** [comment]
First I have to apologize for the slow reply. I had a crazy week... So @bakkeby & @kronikpillow - sorry about that guys!

> Ha, you may want to take that with a pinch of salt :) It's a tinkerer's dream. If anyone ever says that dwm is good then that would be because they have spent those 40+ hours trying out patches, maybe even implemented some, and have fully tailored it to work exactly like they want it to work - it's good because it's good for them.
> Although I use it and being very very happy with it, I can't say that I could ever recommend someone to spend that amount of time fiddling with patches. To be honest it didn't take long before I started hating the patching aspects of dwm. It was time consuming and there was a lot of trial and error. Eventually I got more proficient at it and got to know the code better, even created some patches of my own. I had never done C before.

That's impressive! I mean, you didn't use C before dwm and your work on dwm-flexipatch... From what I saw, you invested a looooooot of time working on it. And you decided to share that with the community which is really nice from you.👍👍

I'm "in the same train" like you were before, I don't have any experience with the C. Although I program websites (I know Javascript, PHP, Bash programming, ...) and don't know much about programming in C but would like to learn it. It would be nice to add that skill to my skill set, so I'm looking forward.🙂 Challenge accepted! 😉

> I used a bash script in the past, but I'd recommend having a look at slstatus instead.
Documentation about slstatus is very poor. I have impression that creators of dwm and especially patches (not all of them but most) purposely wrote poor documentation so that you should read the code and figure out all the functionalities it gave its user at the end. If that's the true, it's not cool, it's not cool at all. But that's the topic for some other occasion 😄

> Eh, yes sure. I have about 60 patches enabled on my flexipatch build, most of them are merely for convenience or just in case I were to break anything. In terms of those that I use most frequently I guess these would be some of my favourites.

I think I will just examine your work (dwm-flexipatch) and try to learn how you did it. I think that's the best way to learn how it needs to be done.

> In terms of layout I use the flextile deluxe layout, it's over the top, but it can do pretty much everything.

You wrote this patch?

I'll check out all the patches you wrote about in the comment above... You gave a lot of material/information worth exploring.

At the end, my final goal regarding dwm is to make my variation of it (I think I can use that word for that 🙂 ) which is going to do everything I need in my everyday work and will serve me for a quite some years to come. Because I don't find fun in using the complete DEs anymore and would like to have completely personalized environment which would suit me perfectly.

I started to use (Neo)Vim because of the same reason - I want to bend the software in the way I want to behave. I don't want to "configure" myself anymore to like some functionality from xy DE which their creators had in mind like a perfect solution. That's not an option for me anymore.🙂 

For the past 10 years (maybe more) I've been using Xfce and Mate but I would really like to switch to this tilling window manager.

> brate moj :) I was doubtfull about the flexipatch build at the beginning, and wanted to go manual patching, but then I realized, that the patches on suckless.org are pretty outdated, that some of them are missing some basic features, and that until I / you actually learn C, and how to properly patch everything, that dwm-flexipatch is the best way to go, as @bakkeby custom tweaked / updated all the patches, and they all shoul work with each other without major conflicts, the ones which conflict between each other are noted in patches.h, so for starters, if you want a functional dwm, and you actually want to test out patches, flexipatch is the best way to go in my opinion, then when and if you learn, and are eager to do the work your self about customizing the patches to your liking, manual patching is the way to go :)

@kronikpillow Oj brate! 🙂 Eto još nekoga sa našega prostora tko se igra sa dwm-om😉
I was fascinated when I saw those few repositories from @bakkeby. That guy did an amazing work, really!👍👍
His dwm-flexipatch is going to make me dwm-addictive 😉, I can see that already.
@kronikpillow  Are you also a programmer?

**Comment by bakkeby** [comment]
> You wrote this patch?

I did yes. I came across the [flextile](https://dwm.suckless.org/patches/flextile/) patch which had the general idea; one layout that can split both horizontally and vertically into a master / stack area, then be able to change between horizontally or vertically arranged tiles in each area independently.

In a sense this made lot of individual layouts redundant, e.g. bstack, bstackhoriz, columns, deck, tile, monocle. I was considering extending flextile to also support the centered master layout, but due to the way it is implemented it would have been very complicated and I'd likely have to rip it apart anyway.

So I had the idea that what if the way the screen is split (master / stack) has absolutely nothing to do with how the tiles are arranged? That simplified a lot of things as the arrange functions only need to worry about tiling client windows within the area given. This also meant that I could easily add support for other arrangements, e.g. various grids or the silly fibonacci (spiral / dwindle) layouts. If you wanted to you could have a grid in the master area and a spiral in the stack area - fun for demonstration purposes even if not that practical.

If I ever end up doing further work on dwm-vanitygaps then I'll likely bring this in, even if it means removing all of the other layouts.

**Comment by igorlakic** [comment]
> So I had the idea that what if the way the screen is split (master / stack) has absolutely nothing to do with how the tiles are arranged? That simplified a lot of things as the arrange functions only need to worry about tiling client windows within the area given. This also meant that I could easily add support for other arrangements, e.g. various grids or the silly fibonacci (spiral / dwindle) layouts. If you wanted to you could have a grid in the master area and a spiral in the stack area - fun for demonstration purposes even if not that practical.

This sounds awesome! You've made a change which opened a bunch of new opportunities in sense of grouping tiles without sacrificing functionality... Are you planing to publish this patch in a separate repository? I think that would be really awesome!

**Comment by kronikpillow** [comment]
@igorlakic yes I'm dwm addicted :D and no, I'm not a fully fledged programmer yet, I'm still learning, but to be a fully fledged programmer is my goal :) I am learning C, thats why I chose dwm, plus I have a very old machine and dwm just works smooth on it ...

@bakkeby is flexipatch now your main focus? and are you going to release diff/patch files for pure dwm of all your latest patches/modifications?

**Comment by bakkeby** [comment]
@kronikpillow yes flexipatch is my main focus - the only reason why I might return to this vanitygaps build in the future is if I'd ever need a demo version of dwm where I can toggle toggle functionality on and off using keyboard shortcuts, like switching between the attach above/below/aside/bottom patches on the fly.

The patches listed on [dwm-flexipatch](https://github.com/bakkeby/dwm-flexipatch) that don't have a link are ones that I don't have diff / patch files for. Currently these are fakefullscreenclient, monitorrules, and flextile-deluxe. I may add patch files for these at some point in the future, but I haven't made that a priority as it's possible to extrapolate most of it using the flexipatch finalizer anyway. The diff, for flextile-deluxe for example, would also depend on whether you take one or more of the pertag, cfacts and vanitygaps patches.

But yes, the general idea is to provide patch files at some point for reference.

**Comment by bakkeby** [comment]
@kronikpillow I guess github issue tracking is not the best place for chats, so I created a slack workspace in case you or Igor have any further questions about the various patches etc.

https://join.slack.com/t/segfault-talk/shared_invite/enQtOTE3MDYyNDYwNzg5LTg3YTQ1OTZmNmExODUzZmI1NzkwZDU3ZWVlYmNhMjg1MGNhMmQ1ZmU3NGRhNjBhYjA4MzFhZGMwOGY1NDI4NzI

I'll just mark this issue as closed now :)

**Comment by igorlakic** [comment]
> @kronikpillow I guess github issue tracking is not the best place for chats, so I created a slack workspace in case you or Igor have any further questions about the various patches etc.
> 
> https://join.slack.com/t/segfault-talk/shared_invite/enQtOTE3MDYyNDYwNzg5LTg3YTQ1OTZmNmExODUzZmI1NzkwZDU3ZWVlYmNhMjg1MGNhMmQ1ZmU3NGRhNjBhYjA4MzFhZGMwOGY1NDI4NzI
> 
> I'll just mark this issue as closed now :)

Sounds like a plan!👍
@bakkeby Thanks once again for your help!
