### ISSUE TITLE
Outer gaps applied twice on single window

### ISSUE THREAD

**Issue by uoou** [bakkeby/dwm-vanitygaps#9]
When there's only a single window visible, the outer gaps are applied one more time than is needed.

    			resize(c, m->wx + ov, m->wy + my, mw - (2*c->bw) - (n > 1 ? oh : 0), h - (2*c->bw), 0);

That seems to fix it (line 60) but I'm not sure it's the ideal way.

**Comment by bakkeby** [comment]
This is a bit unclear. What layout are you referring to?

**Comment by uoou** [comment]
Sorry!

In tiled layout with smart gaps off and only one window on the tag. The gap was applied on the right side twice. Probably not noticeable without fairly large gaps.

**Comment by bakkeby** [comment]
Oh, I see. You are talking about this old patch on the suckless website. I thought it had something to do with this repository.
https://dwm.suckless.org/patches/vanitygaps/dwm-vanitygaps-20190508-6.2.diff

**Comment by uoou** [comment]
Ahh, sorry, I was sure I got it from here.

**Comment by uoou** [comment]
Ok, yeah, just checked on a clean version of dwm with the version offered here and it's fine. 

My apologies.

**Comment by bakkeby** [comment]
Hi @uoou,

I checked the dwm-vanitygaps-20190508-6.2.diff on the suckless website and it seems fine there for single windows.

I noticed that the bottom and right outer gaps were off, but that turned out to be because the resizehints is set to 1 by default. So I don't know, maybe you did get it from here some time in the past.

\
Thanks,

-Stein
